version: "3.9"
services:
  kali:
    image: gbataille/kali:latest
    cap_add:
      - SYS_PTRACE
    container_name: kali
    security_opt:
      - seccomp=unconfined
    volumes:
      - $HOME/Downloads/:/data/Downloads
      - $HOME/Documents/Prog/GITS/CTF/:/data/CTF
      - /tmp:/data/tmp
    tty: true
